name: "Laravel CI & CD"

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ql_ktx_stu

    steps:
    - name: Lấy code
      uses: actions/checkout@v4

    - name: Cài PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: sqlite, mbstring, intl

    - name: Cài Composer
      run: composer install --prefer-dist --no-progress

    - name: Tạo .env
      run: cp .env.example .env

    - name: Generate Key
      run: php artisan key:generate

    - name: Tạo database SQLite
      run: |
        touch database/database.sqlite
        sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env

    - name: Migrate database
      run: php artisan migrate --force



  deploy:
    needs: laravel-tests
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Install Composer Dependencies (Production)
      run: |
        cd ql_ktx_stu
        composer install --no-dev --optimize-autoloader

    - name: Deploy via FTP to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ql_ktx_stu/
        server-dir: /htdocs/ql_ktx_stu/
