name: Laravel CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Lấy code
      uses: actions/checkout@v4

    - name: Cài PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: sqlite, mbstring, intl

    - name: Cài Composer
      run: composer install --prefer-dist --no-progress

    - name: Tạo .env
      run: cp .env.example .env

    - name: Generate Key
      run: php artisan key:generate

    - name: Tạo database SQLite
      run: |
        touch database/database.sqlite
        sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/' .env

    - name: Migrate database
      run: php artisan migrate --force

    - name: Chạy Test
      run: php artisan test
